- name: Create AWS VPC {{ name_prefix }}-vpc
  ec2_vpc_net:
    name: "{{ name_prefix }}-vpc"
    cidr_block: "{{ ptr_zone_cidr }}"
    region: "{{ ec2_region }}"
    tags:
      Username: "{{ skylight_user }}"
      Info: "Username that provisioned this-> {{ skylight_user }}"
      Skylight: "This was provisioned through the skylight provisioner"
      Students: "{{ user_count }}"
  register: create_vpc
  until: create_vpc is not failed
  retries: 5

- name: Set VPC ID
  set_fact:
    ec2_vpc_id: "{{ create_vpc.vpc.id }}"

- name: Create subnet for {{ name_prefix }}-vpc
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    az: "{{ ec2_az }}"
    vpc_id: "{{ ec2_vpc_id }}"
    cidr: "{{ ptr_zone_cidr }}"
    wait_timeout: 600
    resource_tags:
      Name: "{{ name_prefix }}-subnet"
      Username: "{{ skylight_user }}"
      Info: "Username that provisioned this-> {{ skylight_user }}"
      Skylight: "This was provisioned through the skylight provisioner"
      Students: "{{ user_count }}"
  register: create_subnet
  until: create_subnet is not failed
  retries: 15

- name: Set Subnet ID
  set_fact:
    ec2_vpc_subnet_id: "{{ create_subnet.subnet.id }}"

- name: Create Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ ec2_vpc_id }}"
    region: "{{ ec2_region }}"
    tags:
      Name: "{{ name_prefix }}-igw"
      Username: "{{ skylight_user }}"
      Info: "Username that provisioned this-> {{ skylight_user }}"
      Skylight: "This was provisioned through the skylight provisioner"
    state: present
  register: igw
  until: igw is not failed
  retries: 15

- name: vpc public subnet route table is present for {{ ec2_vpc_id }}
  ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    subnets:
      - "{{ ec2_vpc_subnet_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    tags:
      Name: "{{ name_prefix }}-route"
      Username: "{{ skylight_user }}"
      Info: "Username that provisioned this-> {{ skylight_user }}"
      Skylight: "This was provisioned through the skylight provisioner"
      Students: "{{ user_count }}"
  register: routetable
  until: routetable is not failed
  retries: 5

- name: Create ssh key pair for workshop {{ name_prefix }}
  ec2_key:
    name: "{{ skylight_user }}-{{ name_prefix }}-key"
    region: "{{ ec2_region }}"
  register: create_key

- name: Save the private key
  copy:
    content: "{{ create_key.key.private_key }}"
    dest: "{{ playbook_dir }}/workshops/{{ name_prefix }}/{{ skylight_user }}-{{ name_prefix }}-private.pem"
    mode: '0400'
  when: create_key.changed
