---

- include_tasks: resources/aws_check_setup.yml

- include_tasks: resources/find_ami_ids.yml

################### Create Resources ###################
- include_tasks: resources/create_resources.yml

################### Create Security Groups ###################

- include_tasks: resources/security_groups.yml
  loop: "{{ workshops[workshop_type].instances }}"
  loop_control:
    loop_var: app

################### Build Instances ###################

- include_tasks: resources/instances.yml
  loop: "{{ workshops[workshop_type].instances }}"
  loop_control:
    loop_var: app



# Add new dns entries to make the url pretty
#- block:
#
#  - name: "Docs | Create DNS entry for {{ name_prefix }}.{{ public_dns_zone }}"
#    route53:
#      state: present
#      zone: "{{ public_dns_zone }}"
#      record: "{{ name_prefix }}.{{ public_dns_zone }}"
#      type: A
#      ttl: 600
#      value: "{{ item.public_ip }}"
#      wait: yes
#    with_items: "{{ docs_instances.results | map(attribute='tagged_instances') | list }}"

#  - name: "Docs | Create DNS entry for docs.{{ item.tags.long_name }}"
#    route53:
#      state: present
#      zone: "{{ public_dns_zone }}"
#      record: "{{ item.tags.long_name }}"
#      type: A
#      ttl: 600
#      value: "{{ item.public_ip }}"
#      wait: yes
#    with_items: "{{ docs_instances.results | map(attribute='tagged_instances') | list }}"
#
#  - name: "GitLab | Create DNS entry for gitlab.{{ name_prefix }}.{{ public_dns_zone }}"
#    route53:
#      state: present
#      zone: "{{ public_dns_zone }}"
#      record: "{{ item.tags.long_name }}"
#      type: A
#      ttl: 600
#      value: "{{ item.public_ip }}"
#      wait: yes
#    with_items: "{{ gitlab_instances.results | map(attribute='tagged_instances') | list }}"
#
#  - name: "Workstation | Create DNS entries for student workstations"
#    route53:
#      state: present
#      zone: "{{ public_dns_zone }}"
#      record: "{{ item.tags.long_name }}"
#      type: A
#      ttl: 600
#      value: "{{ item.public_ip }}"
#      wait: yes
#    with_items: "{{ workstation_instances.results | map(attribute='tagged_instances') | list }}"

#  when: public_dns_zone is defined


################### Wait for Instances ###################

- include_tasks: resources/connection.yml
  with_dict: "{{ groups }}"
  loop_control:
    loop_var: group
  when:
    - group.key != 'ungrouped'
    - group.key != 'all'

################### Create Inventories ###################

- name: Generate instructor inventory
  template:
    src: instructor_inventory.j2
    dest: "{{ playbook_dir }}/workshops/{{ name_prefix }}/instructor_inventory.txt"

- name: Generate student inventories
  template:
    src: instances.txt.j2
    dest: "{{ playbook_dir }}/workshops/{{ name_prefix }}/{{ user_prefix }}{{ item }}-instances.txt"
  with_sequence: count="{{ user_count }}"
