---
- name: Get the VPC ID for {{ name_prefix }}
  ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: use set fact for easier variables
  set_fact:
    ec2_vpc_id: "{{ vpc_net_facts.vpcs[0].id }}"
  when: vpc_net_facts.vpcs | length > 0

- name: Exit if the VPC doesn't exist
  fail:
    msg: "VPC doesn't exist"
  when: ec2_vpc_id is not defined

- name: grab route information for {{ ec2_name_prefix }} on {{ ec2_region }}
  ec2_vpc_route_table_facts:
    region: "{{ ec2_region }}"
    filters:
      vpc_id: "{{ ec2_vpc_id }}"
  register: route_table_facts
  when: vpc_net_facts.vpcs | length > 0

- name: grab information about AWS user
  aws_caller_facts:
    region: "{{ ec2_region }}"
  register: whoami

- name: save username of AWS user
  set_fact:
    skylight_user: '{{ whoami.arn.split("/")[-1] }}'

# ----------------------- Destroy All Instances -----------------------

- name: Get ec2 instance information
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ ec2_vpc_id }}"
  with_sequence: count={{ user_count }}
  register: ec2_instances

- name: Terminate All Instances
  ec2:
    region: "{{ ec2_region }}"
    state: "absent"
    instance_ids: "{{ item.instances | map(attribute='instance_id') | list }}"
  with_items:
    - "{{ ec2_instances.results }}"
  when: item.instances.0 is defined and item.instances.0.instance_id is defined

# ----------------------- Destroy Workstation DNS -----------------------

- name: Get route53 dns information
  route53:
    state: get
    zone: "{{ public_dns_zone }}"
    record: "{{ name_prefix }}.{{ public_dns_zone }}"
    type: A
  register: route53_dns_record
  when: public_dns_zone is defined

- name: Delete route53 dns alias
  route53:
    state: absent
    zone: "{{ public_dns_zone }}"
    record: "{{ route53_dns_record.set.record }}"
    ttl: "{{ route53_dns_record.set.ttl }}"
    type: "{{ route53_dns_record.set.type }}"
    value: "{{ route53_dns_record.set.value }}"
  when: public_dns_zone is defined and route53_dns_record.set is defined
  ignore_errors: yes

################### Remove Security Groups ###################

- name: Get ec2 security group information
  ec2_group_facts:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ ec2_vpc_id }}"
  with_sequence: count={{ user_count }}
  register: ec2_security_groups

- name: Remove security groups
  ec2_group:
    group_id: "{{ item.group_id }}"
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    state: absent
  when: item.group_name != 'default'
  with_items:
    - "{{ ec2_security_groups.results[0].security_groups }}"
  register: result
  until: result is success
  retries: 20
  delay: 10

################### Remove Everything Else ###################

- name: Remove ssh key pair for workshop {{ name_prefix }}
  ec2_key:
    name: "{{ skylight_user }}-{{ name_prefix }}-key"
    region: "{{ ec2_region }}"
    state: absent
  register: result
  until: result is success
  retries: 20
  delay: 10

- name: Remove subnet for {{ name_prefix }}-vpc
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    cidr: "{{ ptr_zone_cidr }}"
    state: absent
  register: result
  until: result is success
  retries: 20
  delay: 10

- name: Remove Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ ec2_vpc_id }}"
    region: "{{ ec2_region }}"
    tags:
      Name: "{{ name_prefix }}-igw"
    state: absent
  register: result
  until: result is success
  retries: 20
  delay: 10

- name: Remove subnet route table
  ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    route_table_id: "{{ item.id }}"
    lookup: id
    state: absent
  when: item.associations|length == 0
  with_items: "{{ route_table_facts.route_tables }}"
  register: result
  until: result is success
  retries: 5
  delay: 5
  ignore_errors: true

- name: Remove VPC {{ name_prefix }}-vpc
  ec2_vpc_net:
    name: "{{ name_prefix }}-vpc"
    cidr_block: "{{ ptr_zone_cidr }}"
    region: "{{ ec2_region }}"
    state: absent
  register: result
  until: result is success
  retries: 1
  delay: 1
